x-app-env: &app-env
  environment:
    - NGINX_PORT=${NGINX_PORT:-80}
    - WEB_URL=${WEB_URL:-http://localhost}
    - DEBUG=${DEBUG:-0}
    - SENTRY_DSN=${SENTRY_DSN:-""}
    - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-"production"}
    - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-}
    # Gunicorn Workers
    - GUNICORN_WORKERS=${GUNICORN_WORKERS:-1}
    #DB SETTINGS
    - PGHOST=${PGHOST:-plane-db}
    - PGDATABASE=${PGDATABASE:-plane}
    - POSTGRES_USER=${POSTGRES_USER:-plane}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-plane}
    - POSTGRES_DB=${POSTGRES_DB:-plane}
    - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    - PGDATA=${PGDATA:-/var/lib/postgresql/data}
    - DATABASE_URL=${DATABASE_URL:-postgresql://plane:plane@plane-db/plane}
    # REDIS SETTINGS
    - REDIS_HOST=${REDIS_HOST:-plane-redis}
    - REDIS_PORT=${REDIS_PORT:-6379}
    - REDIS_URL=${REDIS_URL:-redis://plane-redis:6379/}

    # RabbitMQ Settings
    - RABBITMQ_HOST=${RABBITMQ_HOST:-plane-mq}
    - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
    - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-plane}
    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-plane}
    - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST:-plane}
    - RABBITMQ_VHOST=${RABBITMQ_VHOST:-plane}
    - AMQP_URL=${AMQP_URL:-amqp://plane:plane@plane-mq:5672/plane}
    # Application secret
    - SECRET_KEY=${SECRET_KEY:-60gp0byfz2dvffa45cxl20p1scy9xbpf6d8c5y0geejgkyp1b5}
    # DATA STORE SETTINGS
    - USE_MINIO=${USE_MINIO:-1}
    - AWS_REGION=${AWS_REGION:-}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-"access-key"}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-"secret-key"}
    - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL:-http://plane-minio:9000}
    - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME:-uploads}
    - MINIO_ROOT_USER=${MINIO_ROOT_USER:-"access-key"}
    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-"secret-key"}
    - BUCKET_NAME=${BUCKET_NAME:-uploads}
    - FILE_SIZE_LIMIT=${FILE_SIZE_LIMIT:-5242880}
    # Live server env
    - API_BASE_URL=${API_BASE_URL:-http://api:8000}

services:
  web:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-frontend:${APP_RELEASE:-stable}
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: if_not_present
    restart: unless-stopped
    command: node web/server.js web
    deploy:
      replicas: ${WEB_REPLICAS:-1}
    depends_on:
      - api
      - worker
    networks:
      - traefik-prismic-plane
      - oim-plane
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-prismic-plane"
      # Middleware
      - 'traefik.http.middlewares.prismic-plane-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.prismic-plane-redirect.redirectscheme.permanent=true'
      # HTTP to HTTPS redirect
      - "traefik.http.routers.prismic-plane-web-http.rule=Host(`plane.prismic.fr`)"
      - "traefik.http.routers.prismic-plane-web-http.entrypoints=web"
      - "traefik.http.routers.prismic-plane-web-http.middlewares=prismic-plane-redirect"
      # HTTPS
      - "traefik.http.routers.prismic-plane-web.rule=Host(`plane.prismic.fr`)"
      - "traefik.http.routers.prismic-plane-web.entrypoints=websecure"
      - "traefik.http.routers.prismic-plane-web.tls=true"
      - "traefik.http.routers.prismic-plane-web.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.prismic-plane-web.loadbalancer.server.port=3000"

  space:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-space:${APP_RELEASE:-stable}
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: if_not_present
    restart: unless-stopped
    command: node space/server.js space
    deploy:
      replicas: ${SPACE_REPLICAS:-1}
    depends_on:
      - api
      - worker
      - web
    networks:
      - oim-plane
      - traefik-prismic-plane
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-prismic-plane"
      - "traefik.http.routers.prismic-plane-spaces.rule=Host(`plane.prismic.fr`) && PathPrefix(`/spaces/`)"
      - "traefik.http.routers.prismic-plane-spaces.entrypoints=websecure"
      - "traefik.http.routers.prismic-plane-spaces.tls=true"
      - "traefik.http.routers.prismic-plane-spaces.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.prismic-plane-spaces.loadbalancer.server.port=3000"

  admin:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-admin:${APP_RELEASE:-stable}
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: if_not_present
    restart: unless-stopped
    command: node admin/server.js admin
    deploy:
      replicas: ${ADMIN_REPLICAS:-1}
    depends_on:
      - api
      - web
    networks:
      - oim-plane
      - traefik-prismic-plane
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-prismic-plane"

      - "traefik.http.routers.prismic-plane-admin-http.rule=Host(`plane.prismic.fr`) && PathPrefix(`/god-mode/`)"
      - "traefik.http.routers.prismic-plane-admin-http.entrypoints=web"
      - "traefik.http.routers.prismic-plane-admin-http.middlewares=prismic-plane-redirect"

      - "traefik.http.routers.prismic-plane-admin.rule=Host(`plane.prismic.fr`) && PathPrefix(`/god-mode/`)"
      - "traefik.http.routers.prismic-plane-admin.entrypoints=websecure"
      - "traefik.http.routers.prismic-plane-admin.tls=true"
      - "traefik.http.routers.prismic-plane-admin.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.prismic-plane-admin.loadbalancer.server.port=3000"

  live:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-live:${APP_RELEASE:-stable}
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: if_not_present
    restart: unless-stopped
    command: node live/dist/server.js live
    deploy:
      replicas: ${LIVE_REPLICAS:-1}
    depends_on:
      - api
      - web
    networks:
      - oim-plane
      - traefik-prismic-plane
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-prismic-plane"
      - "traefik.http.routers.prismic-plane-live.rule=Host(`plane.prismic.fr`) && PathPrefix(`/live/`)"
      - "traefik.http.routers.prismic-plane-live.entrypoints=websecure"
      - "traefik.http.routers.prismic-plane-live.tls=true"
      - "traefik.http.routers.prismic-plane-live.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.prismic-plane-live.loadbalancer.server.port=3000"

  api:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-backend:${APP_RELEASE:-stable}
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: if_not_present
    restart: unless-stopped
    command: ./bin/docker-entrypoint-api.sh
    deploy:
      replicas: ${API_REPLICAS:-1}
    volumes:
      - logs_api:/code/plane/logs
    depends_on:
      - plane-db
      - plane-redis
      - plane-mq
    networks:
      - traefik-prismic-plane
      - oim-plane
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-prismic-plane"
      # HTTP to HTTPS redirect
      # - "traefik.http.routers.prismic-plane-api-http.rule=Host(`plane.prismic.fr`) && PathPrefix(`/auth/`)"
      # - "traefik.http.routers.prismic-plane-api-http.entrypoints=web"
      # - "traefik.http.routers.prismic-plane-api-http.middlewares=prismic-plane-redirect"
      # HTTPS
      # - "traefik.http.routers.prismic-plane-api.rule=Host(`plane.prismic.fr`) && PathPrefix(`/auth/`)"
      - "traefik.http.routers.prismic-plane-api.rule=Host(`plane.prismic.fr`) && (PathPrefix(`/api/`) || PathPrefix(`/auth/`))"
      - "traefik.http.routers.prismic-plane-api.entrypoints=websecure"
      - "traefik.http.routers.prismic-plane-api.tls=true"
      - "traefik.http.routers.prismic-plane-api.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.prismic-plane-api.loadbalancer.server.port=8000"

      - traefik.http.routers.prismic-plane-api.middlewares=prismic-plane-api-cors
      - traefik.http.middlewares.prismic-plane-api-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE
      - traefik.http.middlewares.prismic-plane-api-cors.headers.accessControlAllowOriginList=*
      - traefik.http.middlewares.prismic-plane-api-cors.headers.accessControlAllowHeaders=Content-Type,Authorization


  worker:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-backend:${APP_RELEASE:-stable}
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: if_not_present
    restart: unless-stopped
    command: ./bin/docker-entrypoint-worker.sh
    volumes:
      - logs_worker:/code/plane/logs
    depends_on:
      - api
      - plane-db
      - plane-redis
      - plane-mq
    networks:
      - oim-plane

  beat-worker:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-backend:${APP_RELEASE:-stable}
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: if_not_present
    restart: unless-stopped
    command: ./bin/docker-entrypoint-beat.sh
    volumes:
      - logs_beat-worker:/code/plane/logs
    depends_on:
      - api
      - plane-db
      - plane-redis
      - plane-mq
    networks:
      - oim-plane

  migrator:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-backend:${APP_RELEASE:-stable}
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: if_not_present
    restart: "no"
    command: ./bin/docker-entrypoint-migrator.sh
    volumes:
      - logs_migrator:/code/plane/logs
    depends_on:
      - plane-db
      - plane-redis
    networks:
      - oim-plane

  plane-db:
    <<: *app-env
    image: postgres:15.7-alpine
    pull_policy: if_not_present
    restart: unless-stopped
    command: postgres -c 'max_connections=1000'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - oim-plane

  plane-redis:
    <<: *app-env
    image: valkey/valkey:7.2.5-alpine
    pull_policy: if_not_present
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - oim-plane

  plane-mq:
    <<: *app-env
    image: rabbitmq:3.13.6-management-alpine
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - oim-plane

  plane-minio:
    <<: *app-env
    image: minio/minio:latest
    pull_policy: if_not_present
    restart: unless-stopped
    command: server /export --console-address ":9090"
    volumes:
      - uploads:/export
    networks:
      - oim-plane

  # Comment this if you already have a reverse proxy running
  # proxy:
  #   <<: *app-env
  #   image: ${DOCKERHUB_USER:-makeplane}/plane-proxy:${APP_RELEASE:-stable}
  #   platform: ${DOCKER_PLATFORM:-}
  #   pull_policy: if_not_present
  #   restart: unless-stopped
  #   ports:
  #     - ${NGINX_PORT}:80
  #   depends_on:
  #     - web
  #     - api
  #     - space

volumes:
  pgdata:
  redisdata:
  
  uploads:
  logs_api:
  logs_worker:
  logs_beat-worker:
  logs_migrator:
  rabbitmq_data:

networks:
  traefik-prismic-plane:
    external: true
  oim-plane:
    name: oim-plane
    driver: bridge