name: prismic-keepass

services:

  nginx:
    image: nginx:latest
    container_name: prismic-keepass-nginx
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/keepass:/data
    networks:
      - traefik-prismic-keepass
    labels:
      # Traefik configuration
      - "traefik.enable=true"
      - "traefik.http.routers.prismic-keepass.rule=Host(`keepass.prismic.fr`)"
      - "traefik.http.routers.prismic-keepass.entrypoints=websecure"
      - "traefik.http.routers.prismic-keepass.tls=true"
      - "traefik.http.routers.prismic-keepass.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.prismic-keepass.loadbalancer.server.port=80"

      # Security headers
      - "traefik.http.middlewares.prismic-keepass-security.headers.customresponseheaders.X-Frame-Options=DENY"
      - "traefik.http.middlewares.prismic-keepass-security.headers.customresponseheaders.X-XSS-Protection=1; mode=block"
      - "traefik.http.middlewares.prismic-keepass-security.headers.customresponseheaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.prismic-keepass-security.headers.customresponseheaders.Referrer-Policy=no-referrer"
      - "traefik.http.routers.prismic-keepass.middlewares=prismic-keepass-security"

    restart: unless-stopped

networks:
  traefik-prismic-keepass:
    name: traefik-prismic-keepass
    external: true