name: prismic-static

services:
  defqon:
    image: joseluisq/static-web-server:2
    container_name: prismic-static
    environment:
      # Note: those envs are customizable but also optional
      - SERVER_PORT=8080
      - SERVER_ROOT=/public
      - SERVER_LOG_LEVEL=info
    volumes:
      - ./website:/public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.prismic-static.service=prismic-static"
      - "traefik.http.routers.prismic-static.rule=Host(`static.prismic.fr`)"
      - "traefik.http.routers.prismic-static.entrypoints=websecure"
      - "traefik.http.routers.prismic-static.tls=true"
      - "traefik.http.routers.prismic-static.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.prismic-static.loadbalancer.server.port=8080"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
